<?php

return [
    'alignment_profiles' => [
        'Lawful Good' => [
            'play_well' => 'Be dependable, protect people, and use structure to make life fairer for the group.',
            'watch_out' => 'Do not turn this into policing every ally or blocking the whole table over minor rule-breaking.',
            'starter_trait' => 'I speak plainly and keep promises, even when it is inconvenient.',
            'starter_ideal' => 'Justice. Rules should protect the vulnerable, not excuse cruelty.',
            'starter_bond' => 'My home or order taught me that service matters more than comfort.',
            'starter_flaw' => 'I can be slow to trust people who cut corners, even for good reasons.',
        ],
        'Neutral Good' => [
            'play_well' => 'Lead with kindness and practical help, whether the answer is official or improvised.',
            'watch_out' => 'Do not make the character so agreeable that they stop having convictions or boundaries.',
            'starter_trait' => 'I look for the person most likely to be overlooked and help them first.',
            'starter_ideal' => 'Mercy. If I can make life gentler for someone, I should.',
            'starter_bond' => 'Someone once helped me at the right moment, and I try to repay that gift forward.',
            'starter_flaw' => 'I overextend myself because I hate leaving people unaided.',
        ],
        'Chaotic Good' => [
            'play_well' => 'Fight unfair control, improvise boldly, and still keep loyalty to the party.',
            'watch_out' => 'Do not confuse freedom with randomness or stealing spotlight from everyone else.',
            'starter_trait' => 'I grin at authority when it forgets who it is supposed to serve.',
            'starter_ideal' => 'Freedom. People deserve the right to choose their own path.',
            'starter_bond' => 'I have a soft spot for people trapped by cruel systems.',
            'starter_flaw' => 'The faster a plan sounds official, the more I want to ignore it.',
        ],
        'Lawful Neutral' => [
            'play_well' => 'Be disciplined, consistent, and guided by a code that others can actually understand.',
            'watch_out' => 'Do not become emotionally empty or treat every situation as a courtroom.',
            'starter_trait' => 'I feel calmer when everyone knows the plan and their part in it.',
            'starter_ideal' => 'Order. Clear standards keep chaos from swallowing good intentions.',
            'starter_bond' => 'I owe my loyalty to a tradition, oath, or institution that shaped me.',
            'starter_flaw' => 'I can cling to procedure after the situation has clearly changed.',
        ],
        'Neutral' => [
            'play_well' => 'Stay practical, measured, and focused on what actually works in the moment.',
            'watch_out' => 'Do not play neutrality as apathy; the character should still care about something.',
            'starter_trait' => 'I prefer to study the room before deciding where I stand.',
            'starter_ideal' => 'Balance. Extremes usually create more damage than they solve.',
            'starter_bond' => 'I protect the few people and places that feel steady in an unstable world.',
            'starter_flaw' => 'I can delay hard choices too long while trying to stay even-handed.',
        ],
        'Chaotic Neutral' => [
            'play_well' => 'Value freedom, follow instinct, and stay cooperative with the party even when you resist control.',
            'watch_out' => 'Do not turn this into random sabotage, cruelty, or doing the opposite just to be difficult.',
            'starter_trait' => 'I trust my own instincts faster than other people\'s instructions.',
            'starter_ideal' => 'Freedom. No one gets to own my choices or my future.',
            'starter_bond' => 'A handful of people accept me as I am, and I refuse to let them be caged.',
            'starter_flaw' => 'The moment advice sounds like an order, I want to push back.',
        ],
        'Lawful Evil' => [
            'play_well' => 'If allowed by the table, play ambition, control, and cold discipline without breaking party trust.',
            'watch_out' => 'Check with the DM first; evil works only if the character still has reasons to cooperate.',
            'starter_trait' => 'I stay calm because patience makes power easier to keep.',
            'starter_ideal' => 'Control. The world works best when capable people give the orders.',
            'starter_bond' => 'My name, house, or cause must rise, whatever it costs.',
            'starter_flaw' => 'I excuse harsh choices as long as they move me closer to authority.',
        ],
        'Neutral Evil' => [
            'play_well' => 'If allowed by the table, make selfish choices quietly and strategically instead of chaotically.',
            'watch_out' => 'Check with the DM first; selfish does not mean betraying the campaign every session.',
            'starter_trait' => 'I never forget who owes me and who can be useful later.',
            'starter_ideal' => 'Advantage. If I do not secure my future, nobody else will.',
            'starter_bond' => 'I protect the few assets, secrets, or people that still benefit me.',
            'starter_flaw' => 'I find it hard to make sacrifices that do not pay me back somehow.',
        ],
        'Chaotic Evil' => [
            'play_well' => 'Only use this with clear DM approval, and give the character a reason not to implode the group.',
            'watch_out' => 'This alignment is the easiest way to wreck party play if it is used as an excuse for constant cruelty.',
            'starter_trait' => 'I enjoy seeing fear in people who thought they were untouchable.',
            'starter_ideal' => 'Dominion. If I can take what I want, no higher rule matters.',
            'starter_bond' => 'I obsess over one grudge, hunger, or desire that keeps pulling me forward.',
            'starter_flaw' => 'I burn bridges faster than I can build them.',
        ],
    ],
    'alignment_axis_traits' => [
        'Lawful' => ['Cooperative', 'Loyal', 'Judgmental', 'Methodical'],
        'Chaotic' => ['Boastful', 'Impulsive', 'Rebellious', 'Self-absorbed'],
        'Good' => ['Compassionate', 'Helpful', 'Honest', 'Kind'],
        'Evil' => ['Dishonest', 'Vengeful', 'Cruel', 'Greedy'],
        'Neutral' => ['Selfish', 'Disinterested', 'Laconic', 'Pragmatic'],
    ],
    'roleplay_field_help' => [
        'alignment' => 'Alignment is a short moral compass, not a prison. It should guide choices, not handcuff them.',
        'personality_traits' => 'Think of this as your first impression. One short sentence is enough.',
        'ideals' => 'This is the principle your character wants to live by, such as freedom, duty, knowledge, or kindness.',
        'bonds' => 'A bond is a person, place, oath, or cause important enough to shape major decisions.',
        'flaws' => 'Pick a weakness that creates believable trouble without making the character impossible to adventure with.',
    ],
    'appearance_field_help' => [
        'age' => 'A rough number or life stage is enough, like 19, 42, or 120.',
        'height' => 'Any format is fine, such as 5\'8" or 173 cm.',
        'weight' => 'Any format is fine, such as 160 lb or 72 kg.',
        'eyes' => 'One or two words work well, like gray, bright green, or tired brown.',
        'hair' => 'Color, texture, or style is enough, like black braid or copper curls.',
        'skin' => 'Tone, texture, scars, tattoos, freckles, or unusual features all fit here.',
    ],
    'form_placeholder_profiles' => [
        'default' => [
            'name' => 'Rin, Mara, Toren...',
            'age' => '19, 42, or 120',
            'height' => '173 cm or 5ft 8in',
            'weight' => '72 kg or 160 lb',
            'eyes' => 'Gray, green, amber...',
            'hair' => 'Black braid, copper curls...',
            'skin' => 'Olive, freckled, scarred...',
            'appearance_note' => 'These are lore-style examples for inspiration only. Unusual looks, mixed influences, and custom values all still fit.',
            'name_note' => 'Name ideas can shift with species, but any name is valid at your table.',
        ],
        'species' => [
            'Aasimar' => [
                'name' => 'Seraphine, Cassian, Amaris...',
                'age' => '25 or timeless-looking adult',
                'height' => '170-190 cm is common',
                'weight' => 'Graceful or athletic build',
                'eyes' => 'Gold, silver, pale blue...',
                'hair' => 'White braid, ash blond, dark with a radiant sheen...',
                'skin' => 'Luminous, warm bronze, moon-pale...',
            ],
            'Dragonborn' => [
                'name' => 'Rhogar, Akra, Balasar...',
                'age' => '18 or battle-scarred adult',
                'height' => '180-210 cm is common',
                'weight' => 'Powerful, heavy build',
                'eyes' => 'Amber, ember-red, draconic gold...',
                'hair' => 'Usually none, crest adornments, or frill details',
                'skin' => 'Scaled red, bronze, blue, black...',
            ],
            'Dwarf' => [
                'name' => 'Balin, Hlin, Dagna...',
                'age' => '40 or venerable at 120+',
                'height' => '4ft 2in to 5ft 0in is common',
                'weight' => 'Stout and dense build',
                'eyes' => 'Brown, steel gray, deep green...',
                'hair' => 'Thick beard, braided black, copper plaits...',
                'skin' => 'Weathered tan, ruddy, stone-toned...',
            ],
            'Elf' => [
                'name' => 'Aelar, Lia, Sylvar...',
                'age' => '120 or young by elven standards',
                'height' => '5ft 4in to 6ft 0in is common',
                'weight' => 'Lean, light-footed build',
                'eyes' => 'Green, violet, silver, amber...',
                'hair' => 'Silver fall, midnight braid, copper waves...',
                'skin' => 'Moon-pale, copper, bronze, dusk-toned...',
            ],
            'Gnome' => [
                'name' => 'Nib, Tana, Boddynock...',
                'age' => '40 or bright-eyed elder at 200+',
                'height' => '3ft 0in to 4ft 0in is common',
                'weight' => 'Light and compact build',
                'eyes' => 'Bright blue, hazel, clever green...',
                'hair' => 'Wild copper curls, neat white tuft...',
                'skin' => 'Rosy, nut-brown, freckled...',
            ],
            'Goliath' => [
                'name' => 'Aukan, Manneo, Nalla...',
                'age' => '20 or seasoned peak adult',
                'height' => '6ft 4in to 8ft 0in is common',
                'weight' => 'Heavy, mountain-bred build',
                'eyes' => 'Gray, ice-blue, storm-brown...',
                'hair' => 'Often shaved, braided, or tied for travel',
                'skin' => 'Stone-toned, weather-marked, tattooed...',
            ],
            'Halfling' => [
                'name' => 'Roscoe, Seraphina, Tobin...',
                'age' => '25 or easygoing elder at 90+',
                'height' => '2ft 10in to 3ft 6in is common',
                'weight' => 'Light, sturdy, travel-ready build',
                'eyes' => 'Warm brown, bright green, laughing hazel...',
                'hair' => 'Curly auburn, sandy mop, dark ringlets...',
                'skin' => 'Freckled, sun-browned, rosy...',
            ],
            'Human' => [
                'name' => 'Elara, Tomas, Mira...',
                'age' => '22 or weathered middle age',
                'height' => '165-185 cm is common',
                'weight' => 'Any practical build',
                'eyes' => 'Brown, hazel, blue, gray...',
                'hair' => 'Brown crop, black braid, loose blond curls...',
                'skin' => 'Any tone, sun-worn, freckled, tattooed...',
            ],
            'Orc' => [
                'name' => 'Ghak, Murook, Ovak...',
                'age' => '18 or scarred veteran',
                'height' => '5ft 10in to 6ft 8in is common',
                'weight' => 'Muscular, broad, powerful build',
                'eyes' => 'Gray, amber, deep brown...',
                'hair' => 'Black topknot, shaved sides, heavy braid...',
                'skin' => 'Gray-green, brown, ash-toned...',
            ],
            'Tiefling' => [
                'name' => 'Azra, Kallista, Morthos...',
                'age' => '20 or sharp-featured adult',
                'height' => '160-190 cm is common',
                'weight' => 'Lean or elegant build',
                'eyes' => 'Solid gold, red, violet, ember...',
                'hair' => 'Black waves, white undercut, crimson braid...',
                'skin' => 'Rose, crimson, umber, violet-tinted...',
            ],
        ],
    ],
    'ability_appearance_cues' => [
        'Strength' => [
            'high' => ['Muscular', 'Sinewy', 'Protective', 'Direct'],
            'low' => ['Weak', 'Slight', 'Self-conscious', 'Indirect'],
        ],
        'Dexterity' => [
            'high' => ['Lithe', 'Dynamic', 'Fidgety', 'Poised'],
            'low' => ['Jittery', 'Clumsy', 'Hesitant', 'Unsteady'],
        ],
        'Constitution' => [
            'high' => ['Energetic', 'Hale', 'Hearty', 'Stable'],
            'low' => ['Frail', 'Squeamish', 'Lethargic', 'Fragile'],
        ],
        'Intelligence' => [
            'high' => ['Decisive', 'Logical', 'Informative', 'Curious'],
            'low' => ['Artless', 'Illogical', 'Uninformed', 'Frivolous'],
        ],
        'Wisdom' => [
            'high' => ['Serene', 'Considerate', 'Attentive', 'Wary'],
            'low' => ['Rash', 'Distracted', 'Oblivious', 'Naive'],
        ],
        'Charisma' => [
            'high' => ['Charming', 'Commanding', 'Hilarious', 'Inspiring'],
            'low' => ['Pedantic', 'Humorless', 'Reserved', 'Tactless'],
        ],
    ],
];
